main: me.Khajiitos.KitPvP.KitPvP
name: KitPvPCore
version: 1.0
author: Khajiitos
description: hi
commands:
   elo:
   duel:
   kit:
   ec:
   enderchest:
   preferences:
   spawn:
   gm:
   gamemode:
   money:
   m:
   balance:
   bal:
   shop:
   setmoney:
   enchants:
   setrank:
   broadcast:
   bc:
   msg:
   r:
   respond:
   message:
   discord:
   tempmute:
   unmute:
   invsee:
   ecsee:
   enderchestsee:
   heal:
   feed:
   createwarp:
   removewarp:
   deletewarp:
   warp:
   warps:
   crash:
   vanish:
   freeze:
   walkspeed:
   flyspeed:
   tphere:
   
   